### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by dkumor** [connectordb/connectordb-desktop#2]
The mac version needs 4 things:
- [ ] Keypress frequency logging
- [ ] Window titlebar text
- [ ] Mouse clicks
- [ ] Mac-specific packaging, including run on startup

pyinstaller supposedly can help create a mac package, but has issues with PyQT. I don't know if this is still the case: https://wiki.python.org/moin/PyQt/PyInstallerOnMacOSX

For keyboard logging, this might help: https://gist.github.com/ljos/3019549

Also, you can look at:
https://github.com/karpathy/ulogme
https://github.com/gurgeh/selfspy (you need to be careful here, since it uses a restrictive license (GPL), so if any code from it is used, it needs to be CLEARLY marked as GPL)

I (currently) do not have access to a mac, so I can't implement it myself...

**Comment by dufferzafar** [comment]
There's a new kid in town: https://github.com/sourcegraph/thyme :stuck_out_tongue_closed_eyes: 

Though golang based, you could definitely copy broad ideas...

**Comment by dkumor** [comment]
Thanks for the link! thyme does active window logging much better than laptoplogger, since it is aware of which windows are on the desktop at each moment. It would be nice to imitate the functionality in laptoplogger. While I can't personally work on a mac version (no mac), I think desktop logging on linux and windows can be updated to match thyme.

**Comment by dufferzafar** [comment]
@dkumor thyme executes other commands to get the data. can all of that be done using XLib in pure python?

**Comment by dkumor** [comment]
I am not sure - I'd have to check in detail, but even if xlib isn't enough, laptoplogger can just execute the same commands :) (with attribution, of course).

I'll also look at adding a similar visualization to the connectordb frontend. The beta (to be released near the end of this month) will have plotting/basic stream visualization, which will make it much easier to see what's going on in the data without resorting to python. The alpha (current released version) doesn't include any useful graphing, which makes it much less user-friendly than thyme.

Lastly, as a quick stopgap, it would be super easy to hack together thyme support by reading the generated json file and syncing the data to a connectordb device :)

**Comment by dufferzafar** [comment]
I was thinking that maybe you should decouple the laptoplogger into two parts: gatherers that just dump data + connectordb backend, because not everyone might be into connectordb, but a lot of people do want the computer usage detection. 

I really want to have a proper [ManicTime](http://manictime.com/) alternative for my linux machine, and wouldn't mind writing some code, but I don't want to get into connectordb etc. plain-ol' SQLite seems good enough to me (for now.) 

If later I feel that I need to gather data from multiple machines (like my Android phone etc.) I can setup connectordb and move over from sqlite.

**Comment by dkumor** [comment]
I totally understand your reluctance in trying connectordb. The current version is a real pain to set up, since you need a domain and separate server. If you don't mind running postgres (it is pretty heavy on resources), the new version of laptoplogger will be able to run and manage connectordb locally for you. Furthermore, I think that connectordb will have an sqlite option added at some point.

Having said that, if you're really looking for something lightweight, have you looked into https://github.com/gurgeh/selfspy or https://github.com/karpathy/ulogme? That seems to be very much like what you're describing. Does laptoplogger do something that you are specifically interested in, which selfspy/thyme doesn't do?

**Comment by dufferzafar** [comment]
I'm aware of both selfspy & ulogme, and reading their source is on my to-do list. I read laptoplogger's source last night, and found it to be laid out pretty nicely, so I just thought that it'd be great to have that part separate from the connectordb stuff. With thyme, my foremost gripe is that it is in Go and I'm not too good at it.

I guess I'll have to take the cream out of all these projects myself and see what I can come up with. If I extract out the data gathering part to a separate python package, maybe you could directly use that in laptoplogger?

P.S: I've been trying to come up with a [design of an activity tracking application](http://programmers.stackexchange.com/questions/287822/how-to-design-a-time-tracking-or-activity-monitoring-application) for [quite some time](https://github.com/dufferzafar/time-tracker), so seeing all these new projects is amazing. :smile:

**Comment by dkumor** [comment]
LaptopLogger is MIT licensed, so absolutely feel free to take any code you like from it. If you think you can make it work without needing connectordb, I will happily accept a pull request for that too.

I am on the fence regarding a separate package - you would have to commit to actively maintaining it if laptoplogger is to use it. An alternative would be a separate package in the connectordb namespace, where you would have admin access - that way I'd be comfortable switching laptoplogger over.

Tell me what you think. If you're interested, let's continue this conversation in a separate issue.

**Comment by dkumor** [comment]
PS: Now that I think of it, it would be pretty cool if laptoplogger had pluggable storage backends (sqlite, connectordb, and perhaps others?), so I am pretty interested. Probably wouldn't be able to dedicate much time towards this in the near future, though.

**Comment by dufferzafar** [comment]
I just spent "some" time writing out what I want from a Time Tracker: https://gist.github.com/dufferzafar/1b5861c8c67be4cfc685726686836ca5

Feedback appreciated!

**Comment by dkumor** [comment]
Mac version works, but does not gather data. Created new issue for that (#4)
